name: Build and Deploy

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: priyanshiorufy
        password: orufy@123

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: priyanshiorufy/wisecow-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Configure kubectl
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG}" | base64 --decode > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/wisecow-deployment wisecow-deployment=priyannshiorufy/wisecow-app:latest
        kubectl rollout status deployment/wisecow-deployment
