name: CI/CD Pipeline

on:
  push:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "orufy@123" | docker login -u "priyanshiorufy" --password-stdin

    - name: Build and push Docker image
      run: |
        
        docker push wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl

    - name: Configure kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG" | base64 --decode > $HOME/.kube/config
        kubectl config view

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/wisecow-deployment wisecow-deployment=wisecow-app:latest
        kubectl rollout status deployment/wisecow-deployment
